### ISSUE TITLE
Provide world.schem file

### ISSUE THREAD

**Issue by 0101coding** [GrizzlT/FalconMC#8]
Currently it is not possible to run the server following the guide as it requests for a world.schem file. which though is unnecessary prevents the server from starting. Please provide this file so that I can run the server or remove it from the build so that others do not face the same issue as I have.

**Comment by taylorsk** [comment]
This issue has been fixed and will merge with development soon.
You will now be able to start the server without using a world schematic, by just commenting out, or removing 'world' in falcon.toml

**Comment by GrizzlT** [comment]
This will be closed when the pr gets merged
